version: '3.3'
services:
    deemix:
        image: bocki/deemix
        container_name: Deemix
        volumes:
            - /your/storage/path/:/downloads
            - /your/config/location:/config
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 33333:33333