#!/usr/bin/with-contenv bash

# install deemix

if [ -f "/deemix/updated" ]; then
    echo "[cont-init.d] Installing"
    cd /deemix
    pip3 install -r requirements.txt
    rm /deemix/updated
    echo "[cont-init.d] Installation done"
fi